#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# gistore -- Backup files using DVCS, such as git.
# Copyright (C) 2010 Jiang Xin <jiangxin@ossxp.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Version 0.1 released 2010/1
#

import sys
import os

libpath = os.path.join( os.path.dirname(os.path.realpath(__file__)), 'lib' )
if os.path.exists( os.path.join( libpath, 'gistore' ) ):
    sys.path.insert( 0, os.path.realpath(libpath) )

import gistore

if __name__ == "__main__":
    sys.exit(gistore.main())
